query ($ownName: String!, $repoName: String!) {
  repository(owner: $ownName, name: $repoName) {
    createdAt
    defaultBranchRef {
      name
    }
  }
}
# {"ownName": "CDCGov", "repoName": "llnl.github.io"}
